1\. Find the total mean, and the mean for each row and column of the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [2]:
import numpy as np
m = np.arange(12).reshape((3,4))
print("Matrix:\n",m)

#total mean
print("\nMean value of all elements:\n",np.mean(m))
#mean for each row and for each column
print("\nMean values for each row:\n",np.mean(m, axis=1))
print("Mean value for each column:\n",np.mean(m,axis=0))

Matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Mean value of all elements:
 5.5

Mean values for each row:
 [1.5 5.5 9.5]
Mean value for each column:
 [4. 5. 6. 7.]


2\. Find the outer product of the following vectors:

```python
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])
```

Use different methods to do this:

   1. Using the function `outer` in numpy
   2. Using a nested `for` loop or a list comprehension
   3. Using numpy broadcasting operations

In [12]:
u = np.array([1, 3, 5, 7])
v = np.array([2, 4, 6, 8])

#1)
m = np.outer(u,v)
print("Using outer function of numpy:\n", m)

#2)
#nested for
m = [ [ 0 for i in range(len(u)) ] for j in range(len(v)) ]
for i in range(len(u)):
    for j in range(len(v)):
        m[i][j] = u[i]*v[j]
print("\nNested for method:\n" , m)
#list comprehension

m = np.array( [i*j for i in u for j in v] ).reshape(4,4)
print("\nList compreension:\n" , m)
        
#m=m.reshape((len(u),len(v)))


#3) Broadcasting
m = np.tile(u,(4,1)).T * np.tile(v,(4,1))
print("\nBroadcasting operations:\n" , m)


Using outer function of numpy:
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]

Nested for method:
 [[2, 4, 6, 8], [6, 12, 18, 24], [10, 20, 30, 40], [14, 28, 42, 56]]

List compreension:
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]

Broadcasting operations:
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


3\. Create a 10 by 6 matrix of increasing float numbers, starting from zero and increasing in each step by 0.1, so the output matrix looks like the following:

```python
m = [[0. 0.1, 0.2 0.3 ... 0.9]
     [1.0 1.1 1.2 1.3 ... 1.9]
     ...
     [5.0 5.1 5.2 5.3 ... 5.9]]
```
After creating the matrix, set all entries with a decimal part $< 0.4$ to zero.

In [16]:
m = np.array([[y + 0.1*x for x in range(10)] for y in range(6)])
m.reshape(10,6)
print(m)

for i in range(10):
    for j in range(6):
        if m[i][j]<0.4:
            m[i][j]==0
print(m)

[[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
 [1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
 [2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]
 [3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9]
 [4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9]
 [5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9]]


IndexError: index 6 is out of bounds for axis 0 with size 6

4\. Use `np.linspace` to create an array of 100 numbers between 0 and 2π (inclusive).

  * Extract every 10th element using the slice notation
  * Reverse the array using the slice notation
  * Extract elements where the absolute difference between the sin and cos functions evaluated for that element is $< 0.1$
  * **Optional**: make a plot showing the sin and cos functions and indicate where they are close

In [31]:
m = np.linspace(0, 2*np.pi , 100 , endpoint = True)
print(m)

#normal way
'''a = []
count = 1
for i in range(len(m)+1):
    if i == count*10:
        if i == 100:
            a.append(m[99])
            break
            
        else:    
            a.append(m[i])
            count += 1
      
   
print("\na=",a)'''

#slicing notation

#extract 1 element every 10
b = m[::10]
print("\n b = ",b)

#Reversing the array
reversedB = b[::-1]
print("\n Reversed array = ",reversedB)

#Extracting elements where sin(x)+cos(x)<0.1
cosSin = []
for i in range(len(m)):
    if np.abs(np.cos(m[i])-np.sin(m[i]))<0.1:
        if i == 100:
            cosSin.append(m[i])
            break
        else :
            cosSin.append(m[i])
print("\nArray of |cos(element)-sin(element)<0.1| = ",cosSin)

[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520

5\. Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anti-diagonal matrix (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagonal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [55]:
m = np.tile(np.arange(1,11),(10,1)) #10x10 original matrix
multiplicated = m*m.T  #multiplication to find the requested matrix
#finding the trace:
                            
print("\n Matrix:\n",multiplicated)

#finding the trace
print("\n\nMatrix diagonal:\n",np.diag(multiplicated))
print("\nTrace of the matrix:", np.trace(multiplicated))

#by reversing each row we can find the anti-diagonal 
print("\nAntidiagonal:", np.diag(multiplicated[:][::-1])) 

#finding the diagonal shifted by 1 unit above
print("\nDiagonal (offset = 1 upwards):\n", np.diag(multiplicated, 1))


 Matrix:
 [[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


Matrix diagonal:
 [  1   4   9  16  25  36  49  64  81 100]

Trace of the matrix: 385

Antidiagonal: [10 18 24 28 30 30 28 24 18 10]

Diagonal (offset = 1 upwards):
 [ 2  6 12 20 30 42 56 72 90]


6\. Use broadcasting to create a grid of distances.

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles
The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Build a 2D grid of distances among each city along Route 66
  * Convert the distances in km

In [62]:
def distance(x):
    d = np.tile( x, (len(x), 1) )   
    d=np.abs(d-d.T)
    return d 

Cities = np.array([ "Chicago", "Springfield", "Saint-Louis", "Tulsa", "Oklahoma City", "Amarillo", "Santa Fe", 
"Albuquerque", "Flagstaff", "Los Angeles" ])

xMiles = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])
MilesDistance = distance(xMiles)
print("Distances in Miles:\n\n",MilesDistance)

#in order to convert in km
MilesToKm = 1.60934
print("\n\nDistances in km:\n\n",MilesDistance*MilesToKm)

Distances in Miles:

 [[   0  198  303  736  871 1175 1475 1544 1913 2448]
 [ 198    0  105  538  673  977 1277 1346 1715 2250]
 [ 303  105    0  433  568  872 1172 1241 1610 2145]
 [ 736  538  433    0  135  439  739  808 1177 1712]
 [ 871  673  568  135    0  304  604  673 1042 1577]
 [1175  977  872  439  304    0  300  369  738 1273]
 [1475 1277 1172  739  604  300    0   69  438  973]
 [1544 1346 1241  808  673  369   69    0  369  904]
 [1913 1715 1610 1177 1042  738  438  369    0  535]
 [2448 2250 2145 1712 1577 1273  973  904  535    0]]


Distances in km:

 [[   0.       318.64932  487.63002 1184.47424 1401.73514 1890.9745
  2373.7765  2484.82096 3078.66742 3939.66432]
 [ 318.64932    0.       168.9807   865.82492 1083.08582 1572.32518
  2055.12718 2166.17164 2760.0181  3621.015  ]
 [ 487.63002  168.9807     0.       696.84422  914.10512 1403.34448
  1886.14648 1997.19094 2591.0374  3452.0343 ]
 [1184.47424  865.82492  696.84422    0.       217.2609   706.50026
  1189.30226 1

7\. Prime numbers sieve: compute the prime numbers in the 0-N (start with N=99) range with a sieve (mask).
  * Check the performances (timeit); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)